name: "Deploy"

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      ABSTRA_API_TOKEN: ${{ secrets.ABSTRA_API_TOKEN }}

    steps:
      - name: Cancel Previous runs
        uses: styfle/cancel-workflow-action@0.9.0
        with:
          access_token: ${{ github.token }}

      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Setup
        run: pip install -r requirements.txt

      - name: Deploy
        run: abstra deploy